version: '3.8'

services:
  # Production service
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - weni-cli-network

  # Development service with hot reloading
  api-dev:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - UVICORN_RELOAD=true
    volumes:
      - ./:/app
    restart: unless-stopped
    networks:
      - weni-cli-network

networks:
  weni-cli-network:
    driver: bridge
