name: Build CLI Backend (Push Tag)

on:
  push:
    tags:
      - '*.*.*-develop'
      - '*.*.*-staging'
      - '*.*.*'

jobs:
  call-workflow:
    uses: weni-ai/actions-workflows/.github/workflows/reusable-workflow.yaml@CLOUD-2298
    with:
      image_repository: 869898323958.dkr.ecr.us-east-1.amazonaws.com/cli-backend
      dockerfile: "docker/Dockerfile"
      target_repository: weni-ai/kubernetes-manifests-platform
      target_repository_branch: main
      target_application: cli-backend
      target_patch_file: deployment.json
    secrets: inherit
